### PR TITLE
Update BatchRenorm to Keras 2 API

### PR DESCRIPTION
**Pull request by titu1994**
Updates the BatchRenormalization layer to Keras 2 specifications and should fix the tests as well.

### CODE REVIEW

**Comment by titu1994** [comment]
Theres some bug with Theano. It calls something like ifelse.ifelse which doesnt exist. Is this repository using the master Theano? Keras proper doesnt have errors like this.

**Comment by the-moliver** [comment]
It seems Keras uses the Theano release for tests while we are on bleeding edge here. This seems likely to be the problem. Please submit a bug report to Theano so they can fix. Also I made a PR to switch to using Theano release for tests: https://github.com/farizrahman4u/keras-contrib/pull/72

**Comment by the-moliver** [comment]
Yup that fixed it.

**Comment by titu1994** [comment]
Cool. Thanks.

**Pull request merged**
