### PR TITLE
Added Dead ReLU detector callback

### PR DESCRIPTION
**Pull request by arodiss**
Added new callback which reports the number of dead ReLUs after each training epoch
ReLU is considered to be dead if it did not fire once for entire training set

### CODE REVIEW

**Comment by arodiss** [comment]
`save_load_utils_test.py::test_save_and_load_all_weights()` is failing even on master: https://github.com/farizrahman4u/keras-contrib/pull/116

**Comment by infelane** [comment]
Hi, I updated the dead_relu_detector.py on the following things:
1) Extended layers to everything that has a relu activation
2) Added layer name to the warning
3) Corrected the dead neuron count (should work for both Theano and TF (tested for TF))
4) Added a print alongside the warning since for me the warning stopped showing after some epochs (might be a bug at my side).

However this is my first time working on public github repositories. I'll update if I succeeded in pushing.
I also don't know how I have to work with tests.

**Comment by arodiss** [comment]
@infelane 
Can you please provide link to your pull request?

**Comment by infelane** [comment]
@arodiss 
Link to pull request: https://github.com/farizrahman4u/keras-contrib/pull/174

**Comment by arodiss** [comment]
Thank you @infelane

**Pull request merged**
