### PR TITLE
save_load_utils_test.py removes 'model.h5'

### PR DESCRIPTION
**Pull request by ahundt**
https://github.com/farizrahman4u/keras-contrib/issues/157

If the build passes with this change I'll just merge it.

### CODE REVIEW

**Comment by titu1994** [comment]
Hopefully this fixes the buggy tests.

**Comment by ahundt** [comment]
Apparently it does not fix the bug... but it doesn't break anything either.

**Comment by ahundt** [comment]
Oh it looks like there is some id that occurs twice, and that shouldn't work. @bstriner should the test be changed or the code here?

**Comment by ahundt** [comment]
this at least removes files as the tests should... so I'm merging it

**Pull request merged**
