### PR TITLE
fix dssim, add test

### PR DESCRIPTION
**Pull request by Dref360**
This fix https://github.com/farizrahman4u/keras-contrib/issues/29 and https://github.com/farizrahman4u/keras-contrib/issues/85 .

Added some tests as wel.l

### CODE REVIEW

**Comment by temperatemarine** [comment]
Has #85 been fixed? Can I down load the new package now?

**Comment by Dref360** [comment]
Once this PR get merged.

**Comment by the-moliver** [comment]
Does the TF backend need to be fixed in the same way? And if no, why not?

**Comment by Dref360** [comment]
No Theano `image2neibs` is really different from `tf.extract_image_patches` so the reshaping is easier in tensorflow. The output of images2neibs is : `(nb_windows,windows_height*windows_width*windows_channels)` so you're stuck with some weird reshaping to get the correct order of the windows.

Edit : I added more tests, something I sould've done when I first pushed this feature.

**Comment by temperatemarine** [comment]
I have upgraded keras-contrib to the newest version but my issue as described in #85 still exists . At the line of model.fit(X, y, batch_size=128, epochs=n_epoch, shuffle='batch'), the error is:
`File "/home/ldm/Desktop/SRCNN/SRCNN-hdf5/train.py", line 79, in <module>
    model.fit(X, y, batch_size=128, epochs=n_epoch, shuffle='batch')`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/models.py", line 845, in fit
    initial_epoch=initial_epoch)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 1485, in fit initial_epoch=initial_epoch)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 1140, in _fit_loop outs = f(ins_batch)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1094, in __call__ return self.function(*inputs)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__storage_map=getattr(self.fn, 'storage_map', None))`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op reraise(exc_type, exc_value, exc_trace)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__ self.fn() if output_subset is None else\`
`ValueError: cannot reshape array of size 139392 into shape (128,15488,3,3)`
`Apply node that caused the error: Reshape{4}(Images2Neibs{valid}.0, Join.0)
Toposort index: 113
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector)]
Inputs shapes: [(15488, 9), (4,)]
Inputs strides: [(36, 4), (8,)]
Inputs values: ['not shown', array([  128, 15488,     3,     3])]
Outputs clients: [[InplaceDimShuffle{0,x,1,2,3}(Reshape{4}.0)]]
Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)
  File "/home/ldm/Desktop/SRCNN/SRCNN-hdf5/train.py", line 74, in <module>
    model.compile(loss = DSSIMObjective(), metrics=['mse'], optimizer=adam)
  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/models.py", line 766, in compile
    **kwargs)
  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 899, in compile
    sample_weight, mask)
  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 430, in weighted
    score_array = fn(y_true, y_pred)
  File "build/bdist.linux-x86_64/egg/keras_contrib/losses.py", line 39, in __call__
    patches_pred = KC.extract_image_patches(y_pred, kernel, kernel, 'valid', self.dim_ordering)
  File "build/bdist.linux-x86_64/egg/keras_contrib/backend/theano_backend.py", line 167, in extract_image_patches
    patches = KTH.reshape(patches, (batch, num_channels, KTH.shape(patches)[0] // num_channels, patch_size, patch_size))
  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 713, in reshape
    y = T.reshape(x, shape)
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.`
Still, if dssim was replaced with mse, the program can run:
`model.compile(loss = losses.mean_squared_error, metrics=['mse'], optimizer=adam)`
Both the training (X) and validation (y) data have a shape of (21884,1,33,33).

**Comment by Dref360** [comment]
You will need to pull the repo, since the change has not been pushed to pip.

**Comment by Dref360** [comment]
DSSIMObjective is a class defining a functor.

**Comment by temperatemarine** [comment]
You should use it like this:
model.compile(optimizer=nadam,
                  loss=DSSIMObjective(),
                  metrics=[metrics.mean_absolute_error])

**Pull request merged**
