### PR TITLE
Add Weights for NASNet models

### PR DESCRIPTION
**Pull request by titu1994**
Contains changes to support weight files for NASNet Large and NASNet Mobile

Changes

- Small but important changes to the normal and reduction cells to make them correct
- Support for weight loading for 224 and 331 size inputs when built using the pre-built models

### CODE REVIEW

**Comment by titu1994** [comment]
@ahundt I believe this is now perfect. The weights are loading properly, and the changes ought to be the final major update. Sorry for all the small PRs, this is one hellish model to deal with.

**Comment by ahundt** [comment]
Looks like it was very tricky! I don't think automated use of machine learning to design network models really considers the ease of human re-implementation. :-)

**Comment by titu1994** [comment]
Haha true. This was probably the hardest model I've ever reimplenented in Keras. 

Thankfully, the weight loading mechanism is quite generic, so I can apply it to models in the future. It's just too labour intensive. 

For reference - https://github.com/titu1994/Keras-NASNet/tree/master/weight_translation

**Comment by ahundt** [comment]
Woah cool, you should PR the transfer utilities that are generic here!

**Comment by titu1994** [comment]
Well, it's not generic in that sense. You need to wrap the model with manual weights loading, provided by the manual loading of weights. 

Too much manual work really.

**Pull request merged**
