### PR TITLE
Added PELU Activation Function

### PR DESCRIPTION
**Pull request by joggino**

### CODE REVIEW

**Comment by farizrahman4u** [comment]
Can you please add a unit test too? You can use advanced activations tests in Keras as example.

**Comment by the-moliver** [comment]
Also the documentation is incorrect. Please make sure it accurately reflects what the function actually does as well as all the relevant parameters.

**Comment by farizrahman4u** [comment]
LGTM. @the-moliver Can you confirm?

**Comment by the-moliver** [comment]
I believe implementation is wrong. The `neg` part will be non-zero when x>0, which is not how it should work.

**Comment by farizrahman4u** [comment]
I am not entirely familiar with the concept.. but I guess the issue is here ?
```python
return pos + neg
```

Maybe this will fix it ?
```python
return K.switch(x < 0., neg, pos)
```

**Comment by farizrahman4u** [comment]
I am not entirely familiar with the concept.. but I guess the issue is here ?
```python
return pos + neg
```

Maybe this will fix it ?
```python
return K.switch(x < 0., neg, pos)
```

**Comment by the-moliver** [comment]
That would work. And the `K.relu(x)` in the `pos` part could then be replaced by just `x`.

**Comment by joggino** [comment]
Would you be able to alter:
```
else:
    pos = K.relu(x) * (self.alphas / self.betas)
``` 

to:
```
else:
     pos = x * (self.alphas / self.betas)
``` 

Or should I open another pull request?

**Comment by farizrahman4u** [comment]
Done.

**Pull request merged**
