### PR TITLE
* Add names for layers of dense/transition blocks [DenseNet]

### PR DESCRIPTION
**Pull request by vfdev-5**
For a more simple layers selection, network blocks names are added. Here is an [example](https://gist.github.com/vfdev-5/4a671882d7cb04295f1ddaee784beaa9#file-check_densenet_block_namings-ipynb) of how it looks like with current modifications.

### CODE REVIEW

**Comment by ahundt** [comment]
Can you merge with master for the unit tests?

**Comment by vfdev-5** [comment]
Sorry @ahundt can you detail what you ask me ?

**Comment by ahundt** [comment]
it was passing at the time I wrote it then a change in keras upstream broke keras-contrib. Hopefully it should pass again soon, it looks like everything is passing now except one flaky test.

**Comment by vfdev-5** [comment]
Okay, right, do you still want you to do something special about this PR ?

**Comment by titu1994** [comment]
This is a very useful improvement. @vfdev-5  If you dont mind, can you fix the problems which are perhaps causing tests to fail, and merge this PR?

**Comment by vfdev-5** [comment]
@titu1994 problem is that test fails somewhere in `tests/keras_contrib/utils/save_load_utils_test.py::test_save_and_load_all_weights` with Theano version and it is rather far from what I modified. And actual build state is still failing today...

**Comment by ahundt** [comment]
Changes look ok to me, test failures are unrelated, merging. Thanks!

**Pull request merged**
